FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
EXPOSE 80
EXPOSE 443
WORKDIR /src
COPY ./WebApplication1/WebApplication1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish "WebApplication1/WebApplication1.csproj" -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /publish .

ENTRYPOINT ["dotnet","WebApplication1.dll"]
