name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: modular-e-shop-api # Web App Name
  AZURE_WEBAPP_PACKAGE_PATH: "./publish" # path to pablish directory
  SOLUTION_PATH: ./src/eShop.sln # path to solution

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # change version here
          
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # stored in repository secrets
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
