version: '3.9'
services:
  user-service:
    container_name:   user-service
    ports:
      - "8088:80"
    build:
      context: src/UserService/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  post-service:
    container_name:   post-service
    ports:
      - "8089:80"
    build:
      context: src/PostService/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"